#!/bin/bash
# PreToolUse hook (Edit/Write/NotebookEdit): block edits to the C-reference
# acceptance fixtures and generated files. Exit code 2 blocks the tool call;
# the stderr message is fed back to Claude.
#
# The fixtures under tests/ are the acceptance criteria produced by the original
# C+OpenMP binary; the slow regression gates compare against them. They must
# never change. See CLAUDE.md "Non-negotiable invariants".

file_path=$(python3 -c "import json,sys; print(json.load(sys.stdin).get('tool_input',{}).get('file_path',''))" 2>/dev/null)

[[ -n "$file_path" ]] || exit 0

# Normalise to a repo-relative path for the directory match below.
PROJECT_DIR="${CLAUDE_PROJECT_DIR:-$(pwd)}"
rel="${file_path#"$PROJECT_DIR"/}"

basename=$(basename "$file_path")

# Protected C-reference fixtures (exact files + the master_results directory).
case "$rel" in
    tests/master_results/*|tests/gsetc_params.txt|tests/PFS.20211220.dat|tests/mag_18.dat|tests/analyze_diff.py|tests/gsetc_params_mr.txt|tests/gsetc_params_lr11006.txt|tests/gsetc_params_mr11006.txt|tests/PFS.redMR.20211220.dat|tests/PFS.20240714.dat|tests/PFS.redMR.20240714.dat)
        echo "Blocked: $rel is a read-only C-reference acceptance fixture. The slow regression gates compare against it; it must never be modified. See CLAUDE.md." >&2
        exit 2
        ;;
    legacy/c_src/gsetc.c|legacy/c_src/modeldata.h|legacy/c_src/Makefile)
        echo "Blocked: $rel is the frozen original C ETC source. gsetc.c:<line> citations throughout src/pfsspecsim/etc/ resolve against this exact copy; it must never be modified. See legacy/c_src/README.md." >&2
        exit 2
        ;;
    legacy/python_wrapper/pfsspecsim/*|legacy/python_wrapper/scripts/*)
        echo "Blocked: $rel is part of the frozen pre-2.0 Python wrapper. pfsetc.py:<line> citations throughout src/pfsspecsim/ resolve against this exact copy; it must never be modified. See legacy/python_wrapper/README.md." >&2
        exit 2
        ;;
esac

# Generated files that should be regenerated, not hand-edited.
case "$basename" in
    uv.lock)
        echo "Blocked: uv.lock is generated. Run 'uv sync' / 'uv lock' to regenerate it instead of editing by hand." >&2
        exit 2
        ;;
    _version.py)
        echo "Blocked: _version.py is generated by setuptools-scm from git tags; do not edit it by hand." >&2
        exit 2
        ;;
esac

exit 0
